#pragma once
#include <cstdint>

enum class PacketType : uint16_t {
    // ===== AUTH =====
    AUTH_REGISTER_REQ = 1,
    AUTH_REGISTER_RES,
    AUTH_LOGIN_REQ,
    AUTH_LOGIN_RES,
    AUTH_ACTION_RES = 3,

    // ===== GROUP =====
    GROUP_CREATE_REQ,
    GROUP_CREATE_RES,
    GROUP_JOIN_REQ,
    ROUP_JOIN_RES,
    GROUP_APPROVE_REQ,
    GROUP_APPROVE_RES,
    GROUP_INVITE_REQ,
    GROUP_INVITE_RES,
    GROUP_ACCEPT_INVITE_REQ,
    GROUP_ACCEPT_INVITE_RES,
    GROUP_LEAVE_REQ,
    GROUP_LEAVE_RES,
    GROUP_KICK_REQ,
    GROUP_KICK_RES,
    GROUP_LIST_MEMBERS_REQ,
    GROUP_LIST_MEMBERS_RES,
    GROUP_LIST_REQ,
    GROUP_LIST_RES,
    GROUP_REJECT_REQ = 0x0206,
    GROUP_ACTION_RES = 300,
    GROUP_REJECT_JOIN_REQ,



    // ===== FILE SYSTEM =====
    FILE_LIST_REQ,
    FILE_LIST_RES,

    FILE_MKDIR_REQ,
    FILE_MKDIR_RES,

    FILE_DELETE_REQ,
    FILE_DELETE_RES,

    // ===== FILE TRANSFER =====
    FILE_UPLOAD_REQ,
    FILE_UPLOAD_RES,

    FILE_DOWNLOAD_REQ,
    FILE_DOWNLOAD_RES
};
